[package]
name = "async_object"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

[dependencies.futures]
version="0.3.17"
features = ["thread-pool"]